package main

import (
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

// FieldInfo 字段信息
type FieldInfo struct {
	Name         string // 字段名，如 "Host"
	Type         string // 字段类型，如 "string", "int"
	JSONTag      string // JSON 标签
	Comment      string // 注释
	IsSlice      bool   // 是否为切片
	IsPointer    bool   // 是否为指针
	DefaultValue string // 默认值
}

// StructInfo 结构体信息
type StructInfo struct {
	Name         string      // 结构体名，如 "RedisConfig"
	ReceiverName string      // 接收器名，如 "c"
	PackageName  string      // 包名
	Fields       []FieldInfo // 字段列表
	Imports      []string    // 需要导入的包
}

// 默认值配置
var defaultValues = map[string]map[string]string{
	"RedisConfig": {
		"MaxIdle":      "10",
		"MaxActive":    "500",
		"IdleTimeout":  "240",
		"DialTimeout":  "5",
		"ReadTimeout":  "20",
		"WriteTimeout": "20",
	},
	"MysqlConfig": {
		"MaxOpenConns":    "100",
		"MaxIdleConns":    "10",
		"ConnMaxLifetime": "3600",
		"ConnMaxIdletime": "600",
		"ConnTimeout":     "10",
		"ReadTimeout":     "30",
		"WriteTimeout":    "30",
		"SlowThreshold":   "200",
		"Charset":         "utf8mb4",
	},
}

// 超时字段配置（需要转换为 time.Duration 的字段）
var timeoutFields = map[string]bool{
	"Timeout":         true,
	"IdleTimeout":     true,
	"DialTimeout":     true,
	"ReadTimeout":     true,
	"WriteTimeout":    true,
	"ConnTimeout":     true,
	"ConnMaxLifetime": true,
	"ConnMaxIdletime": true,
}

// 解析 Go 文件
func parseGoFile(filename string) (*StructInfo, error) {
	fset := token.NewFileSet()
	node, err := parser.ParseFile(fset, filename, nil, parser.ParseComments)
	if err != nil {
		return nil, fmt.Errorf("parse file error: %v", err)
	}

	var structInfo *StructInfo

	ast.Inspect(node, func(n ast.Node) bool {
		typeSpec, ok := n.(*ast.TypeSpec)
		if !ok {
			return true
		}

		structType, ok := typeSpec.Type.(*ast.StructType)
		if !ok {
			return true
		}

		structName := typeSpec.Name.Name
		// 只处理以 Config 结尾的结构体
		if !strings.HasSuffix(structName, "Config") {
			return true
		}

		structInfo = &StructInfo{
			Name:         structName,
			ReceiverName: strings.ToLower(string(structName[0])),
			PackageName:  node.Name.Name,
			Fields:       make([]FieldInfo, 0),
			Imports:      []string{},
		}

		// 遍历字段
		for _, field := range structType.Fields.List {
			if len(field.Names) == 0 {
				continue // 跳过匿名字段
			}

			fieldInfo := FieldInfo{
				Name: field.Names[0].Name,
			}

			// 解析字段类型
			fieldInfo.Type = extractType(field.Type)
			fieldInfo.IsSlice = strings.HasPrefix(fieldInfo.Type, "[]")
			fieldInfo.IsPointer = strings.HasPrefix(fieldInfo.Type, "*")

			// 解析 JSON 标签
			if field.Tag != nil {
				tag := field.Tag.Value
				fieldInfo.JSONTag = extractJSONTag(tag)
			}

			// 解析注释
			if field.Comment != nil {
				fieldInfo.Comment = strings.TrimSpace(field.Comment.Text())
			}

			// 设置默认值
			if defaults, ok := defaultValues[structName]; ok {
				if defaultVal, exists := defaults[fieldInfo.Name]; exists {
					fieldInfo.DefaultValue = defaultVal
				}
			}

			structInfo.Fields = append(structInfo.Fields, fieldInfo)
		}

		return false
	})

	if structInfo == nil {
		return nil, fmt.Errorf("no config struct found in file")
	}

	// 检查是否需要导入 time 包
	for _, field := range structInfo.Fields {
		if timeoutFields[field.Name] || strings.Contains(field.Name, "Timeout") {
			structInfo.Imports = append(structInfo.Imports, "time")
			break
		}
		structInfo.Imports = append(structInfo.Imports, "fmt")
	}

	return structInfo, nil
}

// 提取类型字符串
func extractType(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.ArrayType:
		return "[]" + extractType(t.Elt)
	case *ast.StarExpr:
		return "*" + extractType(t.X)
	case *ast.SelectorExpr:
		return fmt.Sprintf("%s.%s", extractType(t.X), t.Sel.Name)
	default:
		return "interface{}"
	}
}

// 提取 JSON 标签
func extractJSONTag(tag string) string {
	tag = strings.Trim(tag, "`")
	parts := strings.Split(tag, " ")
	for _, part := range parts {
		if strings.HasPrefix(part, "json:") {
			jsonTag := strings.Trim(part[5:], `"`)
			// 移除 omitempty 等选项
			if idx := strings.Index(jsonTag, ","); idx > 0 {
				jsonTag = jsonTag[:idx]
			}
			return jsonTag
		}
	}
	return ""
}

// 生成 Getter 方法
func generateGetters(info *StructInfo) string {
	funcMap := template.FuncMap{
		"needsTimeDuration": func(name string) bool {
			return timeoutFields[name] || strings.Contains(name, "Timeout") || strings.Contains(name, "Lifetime")
		},
		"lower": strings.ToLower,
		"title": strings.Title,
	}

	tmpl := `// Code generated by getter-generator. DO NOT EDIT.

package {{.PackageName}}

{{if .Imports}}
import (
{{- range .Imports}}
	"{{.}}"
{{- end}}
)
{{end}}

{{range .Fields}}
{{if eq .Type "string"}}
// Get{{.Name}} 获取 {{.Name}}{{if .Comment}} - {{.Comment}}{{end}}
func ({{$.ReceiverName}} *{{$.Name}}) Get{{.Name}}() string {
	{{if .DefaultValue}}if {{$.ReceiverName}}.{{.Name}} == "" {
		return "{{.DefaultValue}}"
	}
	{{end}}return {{$.ReceiverName}}.{{.Name}}
}
{{else if eq .Type "int"}}
{{if needsTimeDuration .Name}}
// Get{{.Name}} 获取 {{.Name}}{{if .Comment}} - {{.Comment}}{{end}}
func ({{$.ReceiverName}} *{{$.Name}}) Get{{.Name}}() time.Duration {
	{{if .DefaultValue}}if {{$.ReceiverName}}.{{.Name}} <= 0 {
		return time.Duration({{.DefaultValue}}) * time.Second
	}
	{{end}}return time.Duration({{$.ReceiverName}}.{{.Name}}) * time.Second
}
{{else}}
// Get{{.Name}} 获取 {{.Name}}{{if .Comment}} - {{.Comment}}{{end}}
func ({{$.ReceiverName}} *{{$.Name}}) Get{{.Name}}() int {
	{{if .DefaultValue}}if {{$.ReceiverName}}.{{.Name}} <= 0 {
		return {{.DefaultValue}}
	}
	{{end}}return {{$.ReceiverName}}.{{.Name}}
}
{{end}}
{{else if eq .Type "int64"}}
{{if needsTimeDuration .Name}}
// Get{{.Name}} 获取 {{.Name}}{{if .Comment}} - {{.Comment}}{{end}}
func ({{$.ReceiverName}} *{{$.Name}}) Get{{.Name}}() time.Duration {
	{{if .DefaultValue}}if {{$.ReceiverName}}.{{.Name}} <= 0 {
		return time.Duration({{.DefaultValue}}) * time.Second
	}
	{{end}}return time.Duration({{$.ReceiverName}}.{{.Name}}) * time.Second
}
{{else}}
// Get{{.Name}} 获取 {{.Name}}{{if .Comment}} - {{.Comment}}{{end}}
func ({{$.ReceiverName}} *{{$.Name}}) Get{{.Name}}() int64 {
	{{if .DefaultValue}}if {{$.ReceiverName}}.{{.Name}} <= 0 {
		return {{.DefaultValue}}
	}
	{{end}}return {{$.ReceiverName}}.{{.Name}}
}
{{end}}
{{else if eq .Type "bool"}}
// Get{{.Name}} 获取 {{.Name}}{{if .Comment}} - {{.Comment}}{{end}}
func ({{$.ReceiverName}} *{{$.Name}}) Get{{.Name}}() bool {
	return {{$.ReceiverName}}.{{.Name}}
}

// Is{{.Name}} 判断 {{.Name}} 是否启用{{if .Comment}} - {{.Comment}}{{end}}
func ({{$.ReceiverName}} *{{$.Name}}) Is{{.Name}}() bool {
	return {{$.ReceiverName}}.{{.Name}}
}
{{else if .IsSlice}}
// Get{{.Name}} 获取 {{.Name}}{{if .Comment}} - {{.Comment}}{{end}}
func ({{$.ReceiverName}} *{{$.Name}}) Get{{.Name}}() {{.Type}} {
	if {{$.ReceiverName}}.{{.Name}} == nil {
		return make({{.Type}}, 0)
	}
	return {{$.ReceiverName}}.{{.Name}}
}
{{else}}
// Get{{.Name}} 获取 {{.Name}}{{if .Comment}} - {{.Comment}}{{end}}
func ({{$.ReceiverName}} *{{$.Name}}) Get{{.Name}}() {{.Type}} {
	return {{$.ReceiverName}}.{{.Name}}
}
{{end}}
{{end}}
`

	t := template.Must(template.New("getters").Funcs(funcMap).Parse(tmpl))
	var sb strings.Builder
	if err := t.Execute(&sb, info); err != nil {
		fmt.Printf("Template execution error: %v\n", err)
		return ""
	}
	return sb.String()
}

// 生成验证方法
func generateValidator(info *StructInfo) string {
	tmpl := `
// Validate 验证 {{.Name}} 配置
func ({{.ReceiverName}} *{{.Name}}) Validate() error {
	// TODO: 添加验证逻辑
	return nil
}
`
	t := template.Must(template.New("validator").Parse(tmpl))
	var sb strings.Builder
	t.Execute(&sb, info)
	return sb.String()
}

// 生成辅助方法（如 GetAddr）
func generateHelpers(info *StructInfo) string {
	var sb strings.Builder

	// 如果有 Host 和 Port，生成 GetAddr 方法
	hasHost := false
	hasPort := false
	for _, field := range info.Fields {
		if field.Name == "Host" {
			hasHost = true
		}
		if field.Name == "Port" {
			hasPort = true
		}
	}

	if hasHost && hasPort {
		tmpl := `
// GetAddr 获取完整地址
func ({{.ReceiverName}} *{{.Name}}) GetAddr() string {
	return fmt.Sprintf("%s:%d", {{.ReceiverName}}.Host, {{.ReceiverName}}.Port)
}
`
		t := template.Must(template.New("addr").Parse(tmpl))
		t.Execute(&sb, info)

		// 添加 fmt 导入
		found := false
		for _, imp := range info.Imports {
			if imp == "fmt" {
				found = true
				break
			}
		}
		if !found {
			info.Imports = append(info.Imports, "fmt")
		}
	}

	// 如果有 Password，生成 HasPassword 方法
	for _, field := range info.Fields {
		if field.Name == "Password" {
			tmpl := `
// HasPassword 判断是否配置了密码
func ({{.ReceiverName}} *{{.Name}}) HasPassword() bool {
	return {{.ReceiverName}}.Password != ""
}
`
			t := template.Must(template.New("password").Parse(tmpl))
			t.Execute(&sb, info)
			break
		}
	}

	return sb.String()
}

func main() {
	var (
		inputFile  string
		outputFile string
		genHelper  bool
		genValid   bool
	)

	flag.StringVar(&inputFile, "input", "", "输入 Go 文件路径")
	flag.StringVar(&outputFile, "output", "", "输出文件路径（默认为 xxx_gen.go）")
	flag.BoolVar(&genHelper, "helper", true, "是否生成辅助方法")
	flag.BoolVar(&genValid, "validate", false, "是否生成验证方法")
	flag.Parse()

	if inputFile == "" {
		fmt.Println("Usage: go run getter_generator.go -input <file.go> [-output <output.go>] [-helper] [-validate]")
		fmt.Println("\nExample:")
		fmt.Println("  go run getter_generator.go -input redis.go")
		fmt.Println("  go run getter_generator.go -input mysql.go -output mysql_getters.go")
		os.Exit(1)
	}

	// 解析文件
	structInfo, err := parseGoFile(inputFile)
	if err != nil {
		fmt.Printf("Error parsing file: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Found struct: %s with %d fields\n", structInfo.Name, len(structInfo.Fields))

	// 生成代码
	var output strings.Builder

	// 生成 getter 方法
	output.WriteString(generateGetters(structInfo))

	// 生成辅助方法
	if genHelper {
		output.WriteString(generateHelpers(structInfo))
	}

	// 生成验证方法
	if genValid {
		output.WriteString(generateValidator(structInfo))
	}

	// 确定输出文件名
	if outputFile == "" {
		ext := filepath.Ext(inputFile)
		base := strings.TrimSuffix(inputFile, ext)
		outputFile = base + "_gen.go"
	}

	// 写入文件
	if err := os.WriteFile(outputFile, []byte(output.String()), 0644); err != nil {
		fmt.Printf("Error writing file: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated getters saved to: %s\n", outputFile)
}
