-- 创建课件表
CREATE TABLE `courses` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '课件ID',
  `user_id` bigint unsigned NOT NULL COMMENT '用户ID',
  `title` varchar(200) NOT NULL COMMENT '课件标题',
  `description` text COMMENT '课件描述',
  `category` varchar(50) DEFAULT NULL COMMENT '分类',
  `tags` json DEFAULT NULL COMMENT '标签',
  `source_type` enum('url','file','text') NOT NULL COMMENT '内容来源类型',
  `source_content` longtext COMMENT '原始内容',
  `source_url` varchar(500) DEFAULT NULL COMMENT '原始链接',
  `source_file_name` varchar(255) DEFAULT NULL COMMENT '源文件名',
  `source_file_path` varchar(500) DEFAULT NULL COMMENT '源文件路径',
  `thumbnail_url` varchar(500) DEFAULT NULL COMMENT '缩略图URL',
  `status` enum('generating','completed','failed','cancelled') NOT NULL DEFAULT 'generating' COMMENT '状态',
  `error_message` text COMMENT '错误信息',
  `generation_progress` decimal(5,2) DEFAULT '0.00' COMMENT '生成进度百分比',
  `slides_count` int unsigned DEFAULT '0' COMMENT '幻灯片数量',
  `total_duration` int unsigned DEFAULT '0' COMMENT '总时长(秒)',
  `view_count` int unsigned NOT NULL DEFAULT '0' COMMENT '查看次数',
  `like_count` int unsigned NOT NULL DEFAULT '0' COMMENT '点赞数',
  `share_count` int unsigned NOT NULL DEFAULT '0' COMMENT '分享次数',
  `is_public` tinyint unsigned NOT NULL DEFAULT '0' COMMENT '是否公开：0-私有，1-公开',
  `voice_type` varchar(20) DEFAULT 'xiaoyun' COMMENT '语音类型',
  `template_type` varchar(20) DEFAULT 'default' COMMENT '模板类型',
  `generation_params` json DEFAULT NULL COMMENT '生成参数',
  `ai_analysis` json DEFAULT NULL COMMENT 'AI分析结果',
  `completed_at` timestamp NULL DEFAULT NULL COMMENT '完成时间',
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_status` (`status`),
  KEY `idx_category` (`category`),
  KEY `idx_is_public` (`is_public`),
  KEY `idx_created_at` (`created_at`),
  CONSTRAINT `fk_courses_user_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='课件表';